#!/usr/bin/env bash
# AEGIS Twin — the production stack on this machine behind an ngrok HTTPS tunnel (the interim public URL until the
# cloud VM + .tech domain exist; see docs/platform/PHASE8.md).
#
#   ngrok (HTTPS, public) -> Caddy :8090 (SPA + security headers, infra/caddy/Caddyfile) -> API :8100 (AEGIS_ENV=prod)
#                                                                    Reality Emulator (SUMO) -> API, Redis commands
#
# Needs: local Postgres + Redis, .venv, npm, caddy (brew install caddy), ngrok (authtoken configured).
# Secrets and user passwords are generated once into .env.tunnel (git-ignored; keep it private).
# Database aegis_live and Redis DB 5 belong to this stack only (never the dev database, whose demo users would
# otherwise be exposed). Ctrl-C stops everything.
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT=$PWD
ENVF=$ROOT/.env.tunnel
LOG=$ROOT/.tunnel-logs
mkdir -p "$LOG"
PY=$ROOT/.venv/bin/python
API_PORT=8100
EDGE_PORT=${AEGIS_EDGE_PORT:-8090}
DB=aegis_live
REDIS=redis://localhost:6379/5

for p in "$API_PORT" "$EDGE_PORT"; do
  if lsof -iTCP:"$p" -sTCP:LISTEN >/dev/null 2>&1; then echo "port $p is in use (set AEGIS_EDGE_PORT)" >&2; exit 1; fi
done

pids=()
cleanup() { for p in "${pids[@]}"; do kill "$p" 2>/dev/null || true; done; }
trap cleanup EXIT INT TERM

# 1. the public URL first (CORS and the CSP need the origin)
ngrok http "$EDGE_PORT" --log "$LOG/ngrok.log" --log-format logfmt >/dev/null &
pids+=($!)
URL=""
for _ in $(seq 1 30); do
  URL=$(curl -s http://127.0.0.1:4040/api/tunnels | "$PY" -c "import sys, json; t=[x['public_url'] for x in json.load(sys.stdin)['tunnels'] if x['public_url'].startswith('https')]; print(t[0] if t else '')" 2>/dev/null || true)
  [ -n "$URL" ] && break
  sleep 1
done
[ -n "$URL" ] || { echo "ngrok did not start (see $LOG/ngrok.log)" >&2; exit 1; }

# 2. secrets (generated once) + this run's origin
if [ ! -f "$ENVF" ]; then
  "$PY" - "$ENVF" <<'PYEOF'
import secrets, sys
s = lambda n=36: secrets.token_urlsafe(n)
users = ",".join(f"{r}:{r}:{s(12)}" for r in ("admin", "planner", "security", "viewer"))
open(sys.argv[1], "w").write(
    "# generated by scripts/live_tunnel.sh - private, git-ignored\n"
    f"AEGIS_JWT_SECRET={s(48)}\nAEGIS_MASTER_KEY={s()}\nAEGIS_KEY_SECRET={s()}\nAEGIS_PUBLISHER_KEY={s()}\n"
    f"AEGIS_USERS={users}\n")
PYEOF
  chmod 600 "$ENVF"
fi
set -a; source "$ENVF"; set +a
export AEGIS_ENV=prod AEGIS_CORS_ORIGINS="$URL" AEGIS_PUBLISHERS="reality-emulator:$AEGIS_PUBLISHER_KEY"
export AEGIS_DB_URL="postgresql+psycopg://localhost/$DB" AEGIS_REDIS_URL="$REDIS" AEGIS_TWIN_WARMUP_H=58

# 3. a dedicated database at the latest migration, a clean Redis DB
createdb "$DB" 2>/dev/null || true
(cd services/api && "$ROOT/.venv/bin/alembic" upgrade head)
redis-cli -n 5 flushdb >/dev/null

# 4. the SPA, same origin as the API (relative requests)
(cd apps/web && VITE_API_URL="" npm run build >"$LOG/web-build.log" 2>&1)

# 5. API (prod config guard runs at startup), edge, emulator
"$ROOT/.venv/bin/uvicorn" services.api.app.main:app --host 127.0.0.1 --port "$API_PORT" --proxy-headers \
  --forwarded-allow-ips 127.0.0.1 --log-level warning >"$LOG/api.log" 2>&1 &
pids+=($!)
for _ in $(seq 1 120); do curl -fs "http://127.0.0.1:$API_PORT/readyz" >/dev/null 2>&1 && break; sleep 1; done
curl -fs "http://127.0.0.1:$API_PORT/readyz" >/dev/null || { echo "API not ready (see $LOG/api.log)" >&2; exit 1; }

AEGIS_DOMAIN=":$EDGE_PORT" AEGIS_API="127.0.0.1:$API_PORT" AEGIS_WEB_ROOT="$ROOT/apps/web/dist" \
  caddy run --config infra/caddy/Caddyfile --adapter caddyfile >"$LOG/caddy.log" 2>&1 &
pids+=($!)

"$PY" -m sim.reality.run --hours 720 --warmup-h 58 --realtime 60 --http "http://127.0.0.1:$API_PORT" \
  --chaos-redis "$REDIS" --gps-period 2 >"$LOG/emulator.log" 2>&1 &
pids+=($!)

echo "AEGIS Twin is live at $URL"
echo "  sign in with the accounts in .env.tunnel (AEGIS_USERS = user:role:password)"
echo "  logs in $LOG/ · Ctrl-C to stop"
echo "$URL" >"$LOG/url"
wait
