/**
 * Typed access to the static prototype data (generated by scripts/gen_mock.py).
 * In Phase 4+ these become REST/WebSocket calls; the types are the contract.
 */
import networkJson from "../mock/network.json";
import shipmentsJson from "../mock/shipments.json";
import hyderabadJson from "../mock/hyderabad.json";
import scenarioJson from "../mock/scenario.json";
import controlJson from "../mock/control.json";
import trustJson from "../mock/trust.json";
import fidelityJson from "../mock/fidelity.json";
import opsJson from "../mock/ops.json";
import copilotJson from "../mock/copilot.json";

export type NodeType = "port" | "plant" | "supplier" | "dc" | "zone";
export type Mode = "road" | "rail" | "sea" | "air";
export type Sev = "ok" | "warn" | "bad" | "ai" | "good" | "sec";

export interface NetNode {
  id: string; type: NodeType; name: string; lat: number; lon: number; capacity: number;
  attrs: Record<string, unknown>; status: string; betweenness: number; degree: number;
  tts_d: number | null; ttr_d: number | null;
}
export interface Lane {
  id: string; from_id: string; to_id: string; mode: Mode; distance_km: number; cost_per_unit: number;
  capacity: number; co2_per_tkm: number; lt_mu: number; lt_sigma: number; lt_mean_h: number; status: string;
}
export interface Sku { id: string; family: string; name: string; unit_value: number; perishable: boolean; shelf_life_h: number | null; cold_chain: boolean }
export interface InvRow { sku: string; on_hand: number; safety: number; capacity: number; on_order: number; backorder: number }
export interface Shipment {
  id: string; lane_id: string; sku_id: string; qty: number; progress: number; speed: number;
  status: "in_transit" | "at_risk" | "delayed"; eta_h: number; eta_p10_h: number; eta_p90_h: number; vehicle_id: string;
}
export interface Plan {
  id: string; name: string; actions: string[]; cost_lakh: number; service: number; co2_t: number;
  cvar95_lost: number; stockout_p: number; tts_d: number | null; score: number; explain: string;
}
export interface Bands { p10: number[]; p50: number[]; p90: number[] }
export interface Route { from: string; to: string; distance_m: number; duration_s: number; path: [number, number][] }

export const network = networkJson as unknown as {
  nodes: NetNode[]; lanes: Lane[]; skus: Sku[]; inventory: Record<string, InvRow[]>;
};
export const shipments = shipmentsJson as unknown as Shipment[];
export const hyderabad = hyderabadJson as unknown as {
  hubs: { name: string; lat: number; lon: number }[]; routes: Route[]; flood_route_index: number;
  detour: Route; flood_point: [number, number];
};
export const scenario = scenarioJson as unknown as {
  templates: { type: string; label: string; icon: string; target: string; duration_h: number; severity: number }[];
  t_days: number[]; reps: number; node: string; sku: string; safety_stock: number;
  baseline: Bands; mitigated: Bands; air: Bands; tts_d: number; ttr_d: number; plans: Plan[];
  candidates: { id: string; cost_lakh: number; service: number; co2_t: number }[];
  cyclone_polygon: [number, number][]; disrupted_lanes: string[]; reroute_lanes: string[];
};
export const control = controlJson as unknown as {
  kpis: { id: string; label: string; value: number; unit: string; delta: number; state: Sev; spark: number[] }[];
  alerts: { id: string; sev: Sev; t: string; title: string; body: string; node: string | null }[];
  timeline: { hours: number[]; inr_at_risk_cr: number[] };
  weather: { name: string; lat: number; lon: number; wind_kmh: number; rain_mm: number; code: string }[];
  ships: { id: string; lat: number; lon: number; heading: number }[];
};
export interface QEntry { id: string; t: string; source: string; code: string; layer: string; detail: string }
export const trust = trustJson as unknown as {
  layers: { name: string; rejected: number }[];
  sources: { id: string; type: string; trust: number; msgs_min: number; last_seen_s: number; sla_s: number; state: string }[];
  quarantine: QEntry[]; timeline: { m: number; clean: number; rejected: number }[];
  spoof: { vehicle: string; true: [number, number][]; reported: [number, number][] };
  counters: { msgs_24h: number; quarantined_24h: number; attacks_detected: number; mttd_s: number; crashes: number };
  chaos: { id: string; label: string; desc: string; icon: string }[];
};
export const fidelity = fidelityJson as unknown as {
  metrics: { id: string; label: string; value: number; unit: string; target: string; state: Sev }[];
  eta: { t: number[]; actual: number[]; pred: number[]; p10: number[]; p90: number[] };
  reliability: { nominal: number[]; observed: number[] };
  confusion: { labels: string[]; matrix: number[][] };
  decision_value: { policy: string; lost_sales: number; cost: number; co2: number }[];
  wasserstein: { corridor: string; w1_min: number }[];
  drift: { state: string; detail: string };
};
export const ops = opsJson as unknown as {
  pods: { name: string; svc: string; status: string; restarts: number; cpu: number; mem: number; age: string }[];
  loadtest: { tool: string; target_msgs_s: number; peak_msgs_s: number; p95_ms: number; p99_ms: number; error_rate: number; vcpu: number;
    ramp: { vus: number; msgs_s: number; p95_ms: number }[] };
  series: { t: number[]; ingest: number[]; p95: number[]; queue: number[]; ws_clients: number[] };
  slo: { availability: number; target: number; error_budget_left: number };
};
export type CopilotStep =
  | { role: "user" | "assistant"; text: string }
  | { role: "tool"; name: string; args: string; result: string }
  | { role: "proposal"; plan: string };
export const copilot = copilotJson as unknown as { script: CopilotStep[] };

export const nodeById = new Map(network.nodes.map((n) => [n.id, n]));
export const laneById = new Map(network.lanes.map((l) => [l.id, l]));
export const skuById = new Map(network.skus.map((s) => [s.id, s]));
